/*
 * Bilingual meanings & strategy texts for the Qimen chart.
 * Pure data; rendered by js/qimen-app.js.
 */
var QimenData = {

  doors: {
    '開門': { en: 'Open Door', elem: '金', quality: 1,
      zh: '吉門。主開創、事業、見貴，百事可為。',
      enDesc: 'Auspicious. Openings, career, meeting superiors — favorable for almost everything.',
      warZh: '兵法：宜開拔出征、正面進取、求官謁貴。',
      warEn: 'Warcraft: march out, advance openly, seek audience with the powerful.' },
    '休門': { en: 'Rest Door', elem: '水', quality: 1,
      zh: '吉門。主休養、和談、婚聘、謁貴求名。',
      enDesc: 'Auspicious. Rest, peace talks, marriage proposals, gentle advancement.',
      warZh: '兵法：宜休兵養士、締盟議和、以靜制動。',
      warEn: 'Warcraft: rest the troops, negotiate truces, win by stillness.' },
    '生門': { en: 'Life Door', elem: '土', quality: 1,
      zh: '吉門。主生機、求財、營造、養生，大吉。',
      enDesc: 'Auspicious. Vitality, wealth, building, health — the door of growth.',
      warZh: '兵法：生門所在為生路糧道，出師背生門而立，大勝。',
      warEn: 'Warcraft: the supply line and escape route — keep the Life Door at your back to prevail.' },
    '傷門': { en: 'Harm Door', elem: '木', quality: -1,
      zh: '凶門。主損傷、爭鬥；利捕獵、討債、競技。',
      enDesc: 'Inauspicious. Injury and strife; useful only for hunting debts, contests, decisive strikes.',
      warZh: '兵法：宜奇襲爭鋒、擒捕逐北，不宜遠行出師。',
      warEn: 'Warcraft: for raids and pursuit; never for setting out or long marches.' },
    '杜門': { en: 'Obstruction Door', elem: '木', quality: 0,
      zh: '平門，小凶。主閉塞、隱匿；利防守、避災、保密。',
      enDesc: 'Neutral, slightly adverse. Blockage and concealment; good for defense, hiding, secrecy.',
      warZh: '兵法：宜屯兵固守、藏形匿跡、斷敵之道。',
      warEn: 'Warcraft: fortify, conceal your form, cut the enemy’s roads.' },
    '景門': { en: 'Brightness Door', elem: '火', quality: 0,
      zh: '平門。主文書、計謀、宣傳；利考試、獻策、面陳。',
      enDesc: 'Neutral. Documents, plans, publicity; good for exams, proposals, presentations.',
      warZh: '兵法：宜火攻號令、揚旗擂鼓、施計獻策。',
      warEn: 'Warcraft: fire attacks, banners and drums, stratagems and proclamations.' },
    '死門': { en: 'Death Door', elem: '土', quality: -1,
      zh: '凶門。主死滯、終結；利弔喪、漁獵、行刑。',
      enDesc: 'Inauspicious. Stagnation and endings; only fitting for mourning and closing matters.',
      warZh: '兵法：死門為敵之絕地——背生擊死，攻其死方。',
      warEn: 'Warcraft: the enemy’s dead ground — strike toward the Death Door with Life at your back.' },
    '驚門': { en: 'Fright Door', elem: '金', quality: -1,
      zh: '凶門。主驚恐、口舌；利訴訟、設伏、驚敵。',
      enDesc: 'Inauspicious. Alarm and disputes; useful for lawsuits, ambushes, intimidation.',
      warZh: '兵法：宜虛張聲勢、設伏驚敵、以詐佯動。',
      warEn: 'Warcraft: feints and bluster — ambush and unsettle the enemy.' }
  },

  stars: {
    '天蓬': { en: 'Peng · the Raider', elem: '水', quality: -1,
      zh: '凶星，盜賊之宿。智勇而險，忌用事，旺時利冒險求財。',
      enDesc: 'Adverse. The daring raider — clever but risky; avoid major moves.' },
    '天芮': { en: 'Rui · the Ailment', elem: '土', quality: -1,
      zh: '凶星，病星。宜求師學藝、交友；忌醫病、興舉。',
      enDesc: 'Adverse. Star of illness; fine for study and friendship, bad for launching ventures.' },
    '天沖': { en: 'Chong · the Vanguard', elem: '木', quality: 0,
      zh: '平吉，戰神之星。宜出征討伐、急事速行。',
      enDesc: 'Neutral-good. The war vanguard; suits urgent action and decisive campaigns.' },
    '天輔': { en: 'Fu · the Scholar', elem: '木', quality: 1,
      zh: '吉星，文昌之宿。宜文教考試、上書見貴。',
      enDesc: 'Auspicious. The scholar star; excellent for studies, exams, petitions.' },
    '天禽': { en: 'Qin · the Arbiter', elem: '土', quality: 1,
      zh: '吉星，中正之宿。宜謁貴、營造、鎮守中軍。',
      enDesc: 'Auspicious. The impartial center; good for audiences, building, holding the center.' },
    '天心': { en: 'Xin · the General', elem: '金', quality: 1,
      zh: '吉星，將星、醫藥之宿。宜統兵謀略、治病煉丹。',
      enDesc: 'Auspicious. The general and healer; ideal for command, strategy, medicine.' },
    '天柱': { en: 'Zhu · the Breaker', elem: '金', quality: -1,
      zh: '凶星，破壞之宿。宜固守練兵，忌出行興造。',
      enDesc: 'Adverse. The breaker; hold and drill, do not set out or build.' },
    '天任': { en: 'Ren · the Steward', elem: '土', quality: 1,
      zh: '吉星，富星。宜求財置業、遷徙就職。',
      enDesc: 'Auspicious. The steward of wealth; good for money, property, relocation.' },
    '天英': { en: 'Ying · the Beacon', elem: '火', quality: 0,
      zh: '平星，虛名之宿。宜禮儀面試、燈火文書。',
      enDesc: 'Neutral. Bright but hollow; suits ceremony, interviews, presentations.' }
  },

  gods: {
    '值符': { en: 'The Chief', quality: 1,
      zh: '諸神之首，百惡消散。其方大吉，宜倚不宜犯。',
      enDesc: 'Leader of the gods; all evils scatter. Lean on this direction, never move against it.' },
    '螣蛇': { en: 'Soaring Snake', quality: -1,
      zh: '凶神，主虛驚纏繞、怪異多變。',
      enDesc: 'Adverse. False alarms, entanglement, uncanny twists.' },
    '太陰': { en: 'Great Yin', quality: 1,
      zh: '吉神，主陰佑暗助，宜密謀藏形。',
      enDesc: 'Auspicious. Hidden protection; right for quiet plans and concealment.' },
    '六合': { en: 'Six Harmony', quality: 1,
      zh: '吉神，主婚姻交易、聯盟中介。',
      enDesc: 'Auspicious. Marriages, deals, alliances and go-betweens.' },
    '白虎': { en: 'White Tiger', quality: -1,
      zh: '凶神，主刀兵血光、道路傷災。',
      enDesc: 'Adverse. Weapons, blood, road mishaps — the god of violence.' },
    '玄武': { en: 'Black Tortoise', quality: -1,
      zh: '凶神，主盜賊遺失、陰謀詭詐。',
      enDesc: 'Adverse. Theft, loss, schemes and deception.' },
    '九地': { en: 'Nine Earth', quality: 1,
      zh: '吉神，主柔順安穩，宜屯兵固守、深藏。',
      enDesc: 'Auspicious. Yielding stability; entrench, defend, lie low.' },
    '九天': { en: 'Nine Heaven', quality: 1,
      zh: '吉神，主剛健高遠，宜揚兵佈陣、進取遠行。',
      enDesc: 'Auspicious. Vaulting strength; display banners, attack, travel far.' }
  },

  patterns: {
    '青龍返首': { en: 'Blue Dragon Turns Its Head', zh: '大吉之格，百事可為，動則大成。', enDesc: 'Great fortune — act boldly, endeavors succeed.' },
    '飛鳥跌穴': { en: 'Flying Bird Finds the Nest', zh: '大吉之格，時機天成，事半功倍。', enDesc: 'Great fortune — perfect timing, double results for half the effort.' },
    '青龍逃走': { en: 'Blue Dragon Flees', zh: '大凶，主破財失人、下屬離叛。', enDesc: 'Very adverse — losses, desertion, do not act.' },
    '白虎猖狂': { en: 'White Tiger Rampant', zh: '大凶，主刀兵傷災、遠行大忌。', enDesc: 'Very adverse — violence and mishap; no journeys.' },
    '熒入太白': { en: 'Mars Enters Venus', zh: '凶，主賊將至，宜嚴備。', enDesc: 'Adverse — an intruder approaches; guard well.' },
    '太白入熒': { en: 'Venus Enters Mars', zh: '凶，主賊將去，可尋隙而動。', enDesc: 'Adverse — the intruder withdraws; probe carefully.' },
    '朱雀投江': { en: 'Vermilion Bird Dives into the River', zh: '大凶，主文書口舌、音信沉溺。', enDesc: 'Very adverse — documents and messages go astray; lawsuits sour.' },
    '螣蛇夭矯': { en: 'Soaring Snake Writhes', zh: '凶，主纏繞驚恐，文書遲滯。', enDesc: 'Adverse — entanglement and delay.' },
    '大格': { en: 'Great Block', zh: '凶，諸事阻隔，車馬難行。', enDesc: 'Adverse — everything obstructed; travel stalls.' },
    '小格': { en: 'Minor Block', zh: '凶，小有阻滯，謀事艱難。', enDesc: 'Adverse — minor obstructions drag things down.' },
    '刑格': { en: 'Punishment Block', zh: '凶，主刑獄詞訟。', enDesc: 'Adverse — punishments and litigation.' },
    '戰格': { en: 'Battle Block', zh: '凶，金金相爭，主爭戰內耗。', enDesc: 'Adverse — metal clashes metal; infighting.' },
    '伏宮格': { en: 'Hidden Palace Block', zh: '凶，太白伏宮，主暗耗埋伏。', enDesc: 'Adverse — hidden drains and ambushes.' },
    '飛宮格': { en: 'Flying Palace Block', zh: '凶，主奔波爭鬥。', enDesc: 'Adverse — running battles and toil.' },
    '日奇被刑': { en: 'Sun Noble Punished', zh: '凶，乙奇受制，貴人受困。', enDesc: 'Adverse — the helpful noble is constrained.' },
    '凶蛇入獄': { en: 'Vicious Snake Jailed', zh: '凶，主纏訟入獄之象。', enDesc: 'Adverse — entangling litigation.' },
    '螣蛇相纏': { en: 'Snakes Entwined', zh: '凶，主糾纏不清、虛驚。', enDesc: 'Adverse — knots that will not untie.' },
    '幼女姦淫': { en: 'Dishonored Maiden', zh: '凶，主曖昧損名。', enDesc: 'Adverse — scandal and lost reputation.' },
    '沖天奔地': { en: 'Rushing Heaven and Earth', zh: '半吉，主遷移遠行、動盪中有路。', enDesc: 'Mixed — upheaval, yet a road opens for those who move.' },
    '天網四張': { en: 'Heaven’s Net Spreads Wide', zh: '大凶，天羅地網，宜靜守待時。', enDesc: 'Very adverse — the net is spread; stay put and wait.' },
    '奇儀順遂': { en: 'Nobles in Concord', zh: '吉，奇儀相佐，謀為順遂。', enDesc: 'Auspicious — smooth passage for plans.' },
    '奇儀相佐': { en: 'Nobles Assist', zh: '吉，貴人相扶。', enDesc: 'Auspicious — helpful people lend a hand.' },
    '奇儀相合': { en: 'Nobles in Harmony', zh: '吉，陰陽相濟。', enDesc: 'Auspicious — yin and yang cooperate.' },
    '星隨月轉': { en: 'Star Follows the Moon', zh: '吉，主光明漸進。', enDesc: 'Auspicious — steady brightening.' },
    '星奇朱雀': { en: 'Star Noble Vermilion', zh: '吉，利文書信息。', enDesc: 'Auspicious — good for letters and news.' },
    '日月並行': { en: 'Sun and Moon Together', zh: '吉，主功名顯達。', enDesc: 'Auspicious — recognition and advancement.' },
    '三奇得門': { en: 'Three Nobles Meet the Door', zh: '大吉，奇臨吉門，百事俱宜。', enDesc: 'Great fortune — a noble rides an auspicious door.' },
    '玉女守門': { en: 'Jade Maiden Guards the Door', zh: '吉，利交涉幽會、和合之事。', enDesc: 'Auspicious — favorable for meetings, romance, accord.' },
    '伏干格': { en: 'Hidden Stem Clash', zh: '凶，庚伏日干，主暗中受制。', enDesc: 'Adverse — hidden opposition presses the day lord.' },
    '飛干格': { en: 'Flying Stem Clash', zh: '凶，日干飛臨庚上，主正面衝突。', enDesc: 'Adverse — head-on confrontation.' },
    '伏吟': { en: 'Hidden Groan', zh: '凶，天地同宮，主停滯呻吟，宜守不宜動。', enDesc: 'Adverse — stagnation; hold still.' }
  },

  flags: {
    kong:  { zh: '空亡', en: 'Void', desc: '旬空之地，吉凶皆虛，事多落空。', enDesc: 'Void of the xun — outcomes here ring hollow; expect little.' },
    horse: { zh: '馬星', en: 'Horse', desc: '驛馬所在，主動、變、行。', enDesc: 'The travelling horse — movement, change, journeys.' },
    tomb:  { zh: '入墓', en: 'Tomb', desc: '干入墓庫，力量受困難伸。', enDesc: 'The stem is entombed — its strength cannot unfold.' },
    xing:  { zh: '擊刑', en: 'Punished', desc: '六儀擊刑，主刑傷官非。', enDesc: 'Yi punishment — injuries and legal trouble.' },
    menPo: { zh: '門迫', en: 'Forced', desc: '門克宮為迫，吉門減吉，凶門增凶。', enDesc: 'The door forces its palace — good turns weak, bad turns worse.' }
  },

  // 八門司職 — what to route through each door's direction.
  doorUses: {
    '開門': { zh: '出行求官・開業簽約', en: 'set out, seek office, open business, sign deals' },
    '休門': { zh: '和談休整・婚聘謁貴', en: 'negotiate, rest, propose, pay respects' },
    '生門': { zh: '求財營造・置業養生', en: 'seek wealth, build, invest, nurture health' },
    '傷門': { zh: '討債競技・捕捉圍獵', en: 'collect debts, compete, pursue and capture' },
    '杜門': { zh: '避險藏匿・防守保密', en: 'evade risk, hide, defend, keep secrets' },
    '景門': { zh: '考試獻策・宣傳文書', en: 'exams, proposals, publicity, paperwork' },
    '死門': { zh: '弔喪漁獵・了結舊事', en: 'mourning, hunting, closing old matters' },
    '驚門': { zh: '訴訟示威・設伏驚敵', en: 'lawsuits, shows of force, ambush' }
  }
};

if (typeof module === 'object' && module.exports) module.exports = QimenData;
